force-app/main/default/objects/Region__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RegionManagerUtility.cls
public with sharing class RegionManagerUtility {
  private static RegionManagerUtility utility { get; private set; }
  public Map<String, String> responseMap { get; private set; }

  private RegionManagerUtility() {
    this.responseMap = new Map<String, String>();
    List<Region__c> regions = [SELECT Id, Name, Manager__c FROM Region__c];
    for (Region__c region : regions) {
      this.responseMap.put(region.Name, region.Manager__c);
    }
  }

  public static RegionManagerUtility getInstance() {
    if (utility == null) {
      utility = new RegionManagerUtility();
    }
    return utility;
  }
}