force-app/main/default/objects/Order_Status__e/Order_Status__e.object-meta.xml
<CustomObject>
    <label>Order Status</label>
    <pluralLabel>Orders Status</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order_Status__e/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrderTriggerHanlder.cls
/**
 * @description Publish Platform Event Using Apex
 * @Date 25 July 2024
 */
public with sharing class OrderTrigger Hanlder {
    public OrderTriggerHanlder() {

    }

    public static void publishEvent(){
        List<Order_Status__e> orderStatuses = new List<Order_Status__e>();
        List<Order> orderToPublish = [SELECT OrderNumber from Order where Id IN :Trigger.new];
        for(Order ord : orderToPublish){
            Order_Status__e orderStatus = new Order_Status__e(
                Order_Number__c = ord.OrderNumber,
                Total_Amount__c = 0.00   
            );
            orderStatuses.add(orderStatus);
        }

        EventBus.publish(orderStatuses);
    }
}